In [1]:
import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

import pandas as pd

%matplotlib inline

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
# Creacion de constantes
# El valor que retorna el constructos es el valor de la constante

# Creamos constantes a=2 y b=3
a = tf.constant(2)
b = tf.constant(3)
# Creamos matrices de 3x3

matriz1 = tf.constant([[1,3,2], [1,0,0], [1,2,2]])
matriz2 = tf.constant([[1,0,5], [7,5,0],[2,1,1]])

In [7]:
# Realizamos algunos cáculos con estas constantes
suma = tf.add(a,b)
mult = tf.multiply(a,b)
cubo_a = a**3

# suma de matrices 
suma_mat = tf.add(matriz1, matriz2)

# producto de matrices
mult_mat = tf.matmul(matriz1, matriz2)

In [9]:
# Todo en tensorflowocurre dentro de una sesión

# creamos la sesion y realizamos algunas operaciones con las constantes
# y lanzamos la sesión

with tf.Session() as sess:
    print("Suma de las constantes: {}".format(sess.run(suma)))
    print("Multiplicación de las constantes: {}". format(sess.run(mult)))
    print("Constante elevada al cubo: {}".format(sess.run(cubo_a)))
    print("Suma de matrices: \n{}".format(sess.run(suma_mat)))
    print("Producto de matrices: \n{}".format(sess.run(mult_mat)))

Suma de las constantes: 5
Multiplicación de las constantes: 6
Constante elevada al cubo: 8
Suma de matrices: 
[[2 3 7]
 [8 5 0]
 [3 3 3]]
Producto de matrices: 
[[26 17  7]
 [ 1  0  5]
 [19 12  7]]
